# Generated by Django 4.2.30 on 2026-04-20 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
        ('integrations', '0002_whatsappintegration_whatsappsyncedmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarTaskSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('calendar_event_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('synced', 'Synced'), ('failed', 'Failed')], default='synced', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_task_syncs', to='integrations.gmailintegration')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_sync', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_task_syncs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='googlecalendartasksync',
            constraint=models.UniqueConstraint(fields=('user', 'calendar_event_id'), name='unique_google_calendar_event_per_user'),
        ),
    ]
