# Generated by Django 4.2.30 on 2026-04-17 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_email', models.EmailField(max_length=254)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scope', models.TextField(blank=True, default='')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_integration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GmailSyncedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(max_length=255)),
                ('subject', models.TextField(blank=True, default='')),
                ('snippet', models.TextField(blank=True, default='')),
                ('extraction_status', models.CharField(choices=[('created', 'Created'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='created', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_messages', to='integrations.gmailintegration')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gmail_source_messages', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_synced_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='gmailsyncedmessage',
            constraint=models.UniqueConstraint(fields=('user', 'gmail_message_id'), name='unique_gmail_message_per_user'),
        ),
    ]
